language: node_js
node_js:
  - "6"
  - "6.1"

install:
  - npm install -g codecov
  - npm install -g istanbul
script:
  - npm test
  - npm run coverage
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
